# This file contains some arcane technical incantations that are needed to
# enable code coverage tracking via continuous integration.
# It is not an integral part of the project and I'd rather remove it if I could help it.

language: objective-c
osx_image: xcode7.2    
xcode_project: BigInt.xcodeproj
xcode_scheme: BigInt-Mac
after_success: echo "$TRAVIS_JOB_ID"
