name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests
    - name: Run tests
      run: swift test
    - name: Test macOS
      run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-macOS test
    - name: Test iOS
      run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-iOS -destination generic/platform=iOS
    - name: Test watchOS
      run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-watchOS
    - name: Test tvOS
      run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-tvOS
  linux:
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: [bionic, xenial, focal]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery
